# Generated by Django 6.1.1 on 2026-09-05 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0003_alter_servicerequest_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='description',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='title',
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='customer_account',
            field=models.CharField(default='UNKNOWN', max_length=50),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='request_type',
            field=models.CharField(choices=[('LINE_DIAGNOSTIC', 'Line Diagnostic Test'), ('FIRMWARE_UPGRADE', 'Remote Firmware Upgrade'), ('NETWORK_PROVISION', 'Network Provisioning')], db_index=True, default='LINE_DIAGNOSTIC', max_length=30),
        ),
    ]
