# Generated by Django 6.1.1 on 2026-09-05 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0004_remove_servicerequest_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20),
        ),
    ]
